### ISSUE TITLE
 API returned error: 401 (Unauthorized)

### ISSUE THREAD

**Issue by biniamHaddish** [amrro/akane#3]
04-14 13:47:00.804 1797-3216/app.redit E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-7
    Process: app.redit, PID: 1797
    net.dean.jraw.ApiException: API returned error: 401 (Unauthorized), relevant parameters: []
        at net.dean.jraw.models.internal.ObjectBasedApiExceptionStub.create(ObjectBasedApiExceptionStub.java:57)
        at net.dean.jraw.models.internal.ObjectBasedApiExceptionStub.create(ObjectBasedApiExceptionStub.java:33)
        at net.dean.jraw.RedditClient.request(RedditClient.kt:186)
        at net.dean.jraw.RedditClient.request(RedditClient.kt:219)
        at net.dean.jraw.pagination.Paginator.next(Paginator.kt:63)
        at app.redit.data.repo.feed.FeedRemoteDataSource$nextPage$2.invoke(FeedRemoteDataSource.kt:57)
        at app.redit.data.repo.feed.FeedRemoteDataSource$nextPage$2.invoke(FeedRemoteDataSource.kt:12)
        at app.redit.util.ContractsExtensionsKt.buildRequest(ContractsExtensions.kt:28)
        at app.redit.data.repo.feed.FeedRemoteDataSource.nextPage(FeedRemoteDataSource.kt:52)
        at app.redit.data.repo.feed.FeedRepository.updateFrontPage(FeedRepository.kt:50)
        at app.redit.data.repo.feed.FeedRepository.loadMore(FeedRepository.kt:32)
        at app.redit.ui.feed.FeedViewModel$pagedList$1$onItemAtEndLoaded$1.invokeSuspend(FeedViewModel.kt:67)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:234)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
     Caused by: net.dean.jraw.http.NetworkException: HTTP request created unsuccessful response: GET https://oauth.reddit.com/controversial?limit=40&sort=controversial&t=week&after=t3_bcpmha&raw_json=1 -> 401
        at net.dean.jraw.RedditClient.request(RedditClient.kt:186) 
        at net.dean.jraw.RedditClient.request(RedditClient.kt:219) 
        at net.dean.jraw.pagination.Paginator.next(Paginator.kt:63) 
        at app.redit.data.repo.feed.FeedRemoteDataSource$nextPage$2.invoke(FeedRemoteDataSource.kt:57) 
        at app.redit.data.repo.feed.FeedRemoteDataSource$nextPage$2.invoke(FeedRemoteDataSource.kt:12) 
        at app.redit.util.ContractsExtensionsKt.buildRequest(ContractsExtensions.kt:28) 
        at app.redit.data.repo.feed.FeedRemoteDataSource.nextPage(FeedRemoteDataSource.kt:52) 
        at app.redit.data.repo.feed.FeedRepository.updateFrontPage(FeedRepository.kt:50) 
        at app.redit.data.repo.feed.FeedRepository.loadMore(FeedRepository.kt:32) 
        at app.redit.ui.feed.FeedViewModel$pagedList$1$onItemAtEndLoaded$1.invokeSuspend(FeedViewModel.kt:67) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:234) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by amrro** [comment]
It happens with `FeedRemoteDataSource.nextPage()`. It seems it something with renewing the access token. 

If you could give more information on how to regenerate this bug, that would be great.
